// Code generated by "codegen"; DO NOT EDIT.

package code

import code "github.com/mingyuans/goerr-gen/codegen"
import code_174 "github.com/AfterShip/docs-coke-agent-demo/genkit/apps/pkg/code"

// init register error codes defines in this source code to `github.com/mingyuans/errors`
func init() {
	code.Register(ErrUnknown, 500, "Internal server error")
	code.Register(ErrBind, 400, "Error occurred while binding the request body to the struct")
	code.Register(ErrInvalidParams, 400, "Invalid parameter")
	code.Register(ErrValidation, 400, "Validation failed")
	code.Register(ErrTokenInvalid, 401, "Token invalid")
	code.Register(ErrPageNotFound, 404, "Page not found")
	code.Register(ErrTooManyRequests, 429, "You have exceeded the API call rate limit")
	code.Register(ErrDatabase, 500, "Database error")
	code.Register(ErrEncrypt, 401, "Error occurred while encrypting the user password")
	code.Register(ErrSignatureInvalid, 401, "Signature is invalid")
	code.Register(ErrExpired, 401, "Token expired")
	code.Register(ErrInvalidAuthHeader, 401, "Invalid authorization header")
	code.Register(ErrMissingHeader, 401, "The `Authorization` header was empty")
	code.Register(ErrPasswordIncorrect, 401, "Password was incorrect")
	code.Register(ErrPermissionDenied, 403, "Permission denied")
	code.Register(ErrEncodingFailed, 500, "Encoding failed due to an error with the data")
	code.Register(ErrDecodingFailed, 500, "Decoding failed due to an error with the data")
	code.Register(ErrInvalidJSON, 500, "Data is not valid JSON")
	code.Register(ErrEncodingJSON, 500, "JSON data could not be encoded")
	code.Register(ErrDecodingJSON, 500, "JSON data could not be decoded")
	code.Register(ErrInvalidYaml, 500, "Data is not valid Yaml")
	code.Register(ErrEncodingYaml, 500, "Yaml data could not be encoded")
	code.Register(ErrDecodingYaml, 500, "Yaml data could not be decoded")
	code.Register(ErrLockWithFailed, 429, "The resource that is being accessed is locked.Please wait for a moment and try again")
	code.Register(ErrSpannerUnknown, 500, "Spanner unknown error")
	code.Register(ErrESUnknown, 500, "ElasticSearch unknown error")
	code.Register(code_174.Success, 200, "OK")
}
